import Layout from "@/components/layout"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChevronRight } from '@fortawesome/free-solid-svg-icons'
import React from 'react'
import { useEffect, useState } from 'react'
import Image from "next/image";
import Link from "next/link";

type Issue = {
  id: string
  title: string
  priority: string
  priority_icon: string
  last_updated: string
  short_description: string
  status: string
}

type Category = {
  id: string
  name: string
}

type RoadmapData = {
  categories: Category[]
  issues: { [key: string]: Issue[] }
}

const RoadmapPage = () => {
  const [roadmapData, setRoadmapData] = useState<RoadmapData>()

  useEffect(() => {
    const fetchRoadmapData = async () => {
      const res = await fetch("/api/roadmap")
      const data = await res.json()
      setRoadmapData(data)
    }
    fetchRoadmapData()
  }, [])

  if (!roadmapData || typeof(roadmapData) === "undefined") {
    return (
        <Layout>
            <div className="ss">Loading...</div>
        </Layout>
    )
  }

  const columnWidth = `${100 / roadmapData.categories.length}%`;
  const columnClass = `max-w-screen-lg w-full md:w-${columnWidth}`;
  const emSizeInPixels = parseFloat(getComputedStyle(document.documentElement).fontSize);


  return (
    <Layout>
      <div className="flex flex-col w-12/12 md:w-10/12 xl:w-8/12 gap-4 p-4 md:flex-row">
        {roadmapData.categories.map((category) => (
          <div key={category.id} className={columnClass}>
            <h2 className="text-lg font-semibold mb-2 p-2">{category.name}</h2>
            <div className="flex flex-col gap-4">
                {roadmapData.issues[category.id].sort((a, b) => a.title.localeCompare(b.title)).map((issue) => (
                  <Link key={issue.id} href={`/roadmap/${issue.id}`} className="no-underline">
                    <div className="p-4 cursor-pointer rounded-md border border-zinc-900 bg-zinc-900/90 shadow-xl">
                      <div className="flex flex-row gap-4 items-center">
                        <div className="w-8 h-8 relative">
                          <Image className="inline-flex"
                            src={issue.priority_icon}
                            alt={issue.priority}
                            width={`${1 * emSizeInPixels}`}
                            height={`${1 * emSizeInPixels}`}
                          />
                        </div>
                        <div className="flex-grow">
                          <h3 className="text-base font-semibold">{issue.title}</h3>
                          <p className="text-sm text-gray-300">
                            {issue.short_description}
                          </p>
                        </div>
                        <FontAwesomeIcon icon={faChevronRight} size="lg" className="h-5 w-5 text-gray-200" />
                      </div>
                    </div>
                  </Link>
                ))}
            </div>
          </div>
        ))}
      </div>
      <div className="text-sm w-full text-center bg-zinc-900/90 p-5 shadow-xl">
          This page was automatically generated by the live data on Jira (the project management system).<br />Some styles or design might be broken.
      </div>
    </Layout>
  )

}

export default RoadmapPage
